### ISSUE TITLE
Recompile of 0.3.0 needed for play-json 2.4.x...

### ISSUE THREAD

**Issue by bplawler** [flyberry-capital/scala-slack#2]
We were using `scala-slack` for years with our Play2.2, then 2.3 application but when we went to Play 2.4.11 we got the following exception:

```
play.api.libs.json.JsValue.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue;
        at com.flyberrycapital.slack.HttpClient.checkResponse(HttpClient.scala:46)
        at com.flyberrycapital.slack.HttpClient.post(HttpClient.scala:91)
        at com.flyberrycapital.slack.Methods.Chat.postMessage(Chat.scala:80)
        at ...
```

The `$bslash` method has existed forever in play-json, but in 2.4.x it no longer returns `play/api/libs/json/JsValue` (now it returns `JsLookupResult` - see https://www.playframework.com/documentation/2.4.x/Migration24#json-api-changes).  The code here on `master` looks correct, but the published version (0.3.0) of the jar still expects the old version of the `$bslash`.  So I think just a recompile and a version bump (0.3.1) would do the trick?

Meantime, we have to download and compile ourselves...

**Comment by ksolan** [comment]
Thanks for letting me know -- bumped the play-json dep to v2.6.6 in the meantime as well. v0.3.1 should be hitting Maven central shortly.

**Comment by shogun656** [comment]
@ksolan Hey, I am getting the same error. Any update on when the v0.3.1 is going to hit Maven?

**Comment by ksolan** [comment]
It should be on maven now! https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.flyberrycapital%22 Lemme know if you're still seeing this issue.

**Comment by shogun656** [comment]
Can you update the Readme to show 0.3.1? Thank you for the quick response though. It is working perfect on my end

**Comment by ksolan** [comment]
Just did! Thanks for flagging.
